const Menu=[
    {
        id:1,
        name:'Jalebi',
        category:'Breakfast',
        image:'image/jilebi.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :20/-',
    },
    {
        id:2,
        name:'frutechat',
        category:'Breakfast',
        image:'image/frutechat.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :20/-',
    },
    {
        id:3,
        name:'Dal_Chaval',
        category:'Lunch',
        image:'image/dal_chaval.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :120/-',
    },
    {
        id:4,
        name:'Sabji_Roti',
        category:'Lunch',
        image:'image/sabji_roti.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :150/-',
    },
    {
        id:5,
        name:'Samosha',
        category:'Snacks',
        image:'image/samosha.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :25/-',
    },
    {
        id:6,
        name:'Aaloo_Chup',
        category:'Snacks',
        image:'image/chup.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :15/-',
    },
    {
        id:7,
        name:'Butter Paneer',
        category:'Dinner',
        image:'image/paneer.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :220/-',
    },
    {
        id:8,
        name:'Chiken',
        category:'Dinner',
        image:'image/Chiken.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :260/-',
    },
];
export default Menu
