const Menu=[
    {
        id:1,
        name:'Jalebi',
        category:'Breakfast',
        image:'image/jilebi.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :20/-',
    },
    {
        id:2,
        name:'frutechat',
        category:'Breakfast',
        image:'image/frutechat.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :30/-',
    },
    {
        id:3,
        name:'Chai_Poha',
        category:'Breakfast',
        image:'image/poha.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :25/-',
    },
    {
        id:4,
        name:'Aamlet',
        category:'Breakfast',
        image:'image/aamlet.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :20/-',
    },
    {
        id:5,
        name:'Paneer Dosa',
        category:'Lunch',
        image:'image/paneer_dosa.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :110/-',
    },
    {
        id:6,
        name:'Dal_Chaval',
        category:'Lunch',
        image:'image/dal_chaval.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :120/-',
    },
   
    {
        id:7,
        name:'Sabji_Roti',
        category:'Lunch',
        image:'image/sabji_roti.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :150/-',
    },
    {
        id:8,
        name:'Chhola_Bhatura',
        category:'Lunch',
        image:'image/chhola_bhatura.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :90/-',
    },
 
    {
        id:9,
        name:'Samosha',
        category:'Snacks',
        image:'image/samosha.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :20/-',
    },
 
    {
        id:10,
        name:'Aaloo_Chup',
        category:'Snacks',
        image:'image/chup.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :15/-',
    },
    {
        id:11,
        name:'Idli',
        category:'Snacks',
        image:'image/idli.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :25/-',
    },
    {
        id:12,
        name:'Momos',
        category:'Snacks',
        image:'image/momos.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :30/-',
    },
    {
        id:13,
        name:'Butter Paneer',
        category:'Dinner',
        image:'image/paneer.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :220/-',
    },
    {
        id:14,
        name:'Puri_Sabji',
        category:'Dinner',
        image:'image/puri_sabji.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :180/-',
    },
    {
        id:15,
        name:'Fish_Curry',
        category:'Dinner',
        image:'image/fish_curry.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :240/-',
    },
    {
        id:16,
        name:'Chiken',
        category:'Dinner',
        image:'image/Chiken.jpg',
        detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis cumque dolore vero voluptatum est harum nulla enim autem quisquam sed minus aperiam, esse fuga odio.',
        price: 'PRICE :260/-',
    },
];
export default Menu


